name: PR Approval check

on:
  pull_request:
    branches: [ master ]
  pull_request_review:
    branches: [ master ]

jobs:
  check_approvals:
    runs-on: ubuntu-latest
    steps:
      - name: Approval Checks
        uses: ./.github/actions
        with:
          rules: >
            approval:
              - name: "Required approval for live section"
                min:
                  count: 2
                when:
                  fileSetContains: '^live\/'
                required:
                  reviewers: [ ]
                  teams: [ "jlescanciano-n26-sample/default-team" ]
              - name: "Required approval for proposal section"
                min:
                  count: 1
                when:
                  fileSetContains: '^proposal\/'
                required:
                  reviewers: [ ]
                  teams: [ "jlescanciano-n26-sample/default-team", "n26/cant-access" ]
